### ISSUE TITLE
CI/e2e broken

### ISSUE THREAD

**Issue by vdice** [brigadecore/kashti#237]
Looks like CI is broken due to failing e2e... here's the crux of the output from `ng e2e`:
```
...
[22:44:09] I/direct - Using ChromeDriver directly...
[22:44:09] E/launcher - session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1030-azure x86_64)
[22:44:09] E/launcher - SessionNotCreatedError: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1030-azure x86_64)
    at Object.checkLegacyResponse (/src/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/src/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/src/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/src/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/src/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/src/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/src/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/src/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/src/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/src/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/src/node_modules/q/q.js:796:13)
    at /src/node_modules/q/q.js:556:49
    at runSingle (/src/node_modules/q/q.js:137:13)
[22:44:09] E/launcher - Process exited with error code 199
An unexpected error occurred: undefined
```

All due to `SessionNotCreatedError: session not created: Chrome version must be between 70 and 73` maybe?  Perhaps a matter of dependency updates/wrangling 😬 ?

**Comment by anarang** [comment]
I am facing the same issue, any updates on this?

**Comment by radu-matei** [comment]
Investigating, thanks for reporting!

**Comment by radu-matei** [comment]
You have to love the obscure Node-ecosystem issues...

Just deleted `node_modules`, did a `yarn install`, followed by a `yarn e2e`:

```
radu:kashti$ yarn e2e
yarn run v1.5.1
$ ng e2e
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2019-01-28T13:03:24.804Z
Hash: 4b442d0444a92566713c
Time: 8133ms
chunk {main} main.js, main.js.map (main) 274 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 226 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 238 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 264 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.99 MB [initial] [rendered]
[15:03:25] I/file_manager - creating folder /Users/radu/go/src/github.com/Azure/kashti/node_modules/webdriver-manager/selenium
[15:03:25] I/config_source - curl -o/Users/radu/go/src/github.com/Azure/kashti/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
ℹ ｢wdm｣: Compiled successfully.
[15:03:25] I/downloader - curl -o/Users/radu/go/src/github.com/Azure/kashti/node_modules/webdriver-manager/selenium/chromedriver_2.45.zip https://chromedriver.storage.googleapis.com/2.45/chromedrive
r_mac64.zip
[15:03:28] I/update - chromedriver: unzipping chromedriver_2.45.zip
[15:03:28] I/update - chromedriver: setting permissions to 0755 for /Users/radu/go/src/github.com/Azure/kashti/node_modules/webdriver-manager/selenium/chromedriver_2.45
[15:03:29] I/launcher - Running 1 instances of WebDriver
[15:03:29] I/direct - Using ChromeDriver directly...
Jasmine started

  kashti App

    kashti main page
      ✓ should redirect to /dashboard
      ✓ should have a title

    sidebar
      ✓ should be present
      ✓ should have a link to the kashti main page
      ✓ should have a link to the Kashti docs
      ✓ should have a link to the Kashti issues

Executed 6 of 6 specs SUCCESS in 7 secs.
[15:03:37] I/launcher - 0 instance(s) of WebDriver still running
[15:03:37] I/launcher - chrome #01 passed
✨  Done in 23.64s.
```

At least this is an obscure error that fixed itself.
Closing, but feel free to re-open if you still experience this.

Thanks!

**Comment by vdice** [comment]
Darn, although I can confirm the tests pass on my box when following the steps above, CI still fails due to 
```
[17:11:33] I/direct - Using ChromeDriver directly...
[17:11:34] E/launcher - session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1036-azure x86_64)
[17:11:34] E/launcher - SessionNotCreatedError: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1036-azure x86_64)
    at Object.checkLegacyResponse (/src/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/src/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/src/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/src/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/src/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/src/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/src/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/src/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/src/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/src/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/src/node_modules/q/q.js:796:13)
    at /src/node_modules/q/q.js:556:49
    at runSingle (/src/node_modules/q/q.js:137:13)
[17:11:34] E/launcher - Process exited with error code 199
An unexpected error occurred: undefined
```
See https://azure.github.io/kashti/jobs/kashti-e2e-01d2jdmps9bxh40y3fwb61y8yz

**Comment by vdice** [comment]
Fixed in https://github.com/brigadecore/kashti/pull/249; Closing.
